server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;
    location /plp/ {
        rewrite ^/plp/(.*)$ /$1 break;
        try_files $uri $uri/ /index.html;
    }
}
